
CREATE TABLE  DM_CATEGORIA (
  CODCAT VARCHAR(2) NOT NULL,
  DESCAT VARCHAR(45) NOT NULL,
  PRIMARY KEY (CODCAT));


CREATE TABLE  DM_PRODUCTO (
  CODPRO VARCHAR(6) NOT NULL,
  DESPRO VARCHAR(100) NOT NULL,
  PREPRO DECIMAL NOT NULL,
  CODCAT VARCHAR(2) NOT NULL,
  PRIMARY KEY (CODPRO),
  INDEX fk_DM_PRODUCTO_DM_CATEGORIA_idx (CODCAT ASC),
  CONSTRAINT fk_DM_PRODUCTO_DM_CATEGORIA
    FOREIGN KEY (CODCAT)
    REFERENCES DM_CATEGORIA (CODCAT)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE  DM_UBIGEO (
  CODUBI VARCHAR(2) NOT NULL,
  DESDEP VARCHAR(100) NOT NULL,
  DESPRO VARCHAR(100) NOT NULL,
  DESDIS VARCHAR(100) NOT NULL,
  PRIMARY KEY (CODUBI));


CREATE TABLE  DM_SUCURSAL (
  CODSUC VARCHAR(4) NOT NULL,
  DESSUC VARCHAR(50) NOT NULL,
  DIRSUC VARCHAR(200) NULL,
  TELSUC VARCHAR(20) NULL,
  CODUBI VARCHAR(2) NOT NULL,
  PRIMARY KEY (CODSUC),
  INDEX fk_DM_SUCURSAL_DM_UBIGEO1_idx (CODUBI ASC),
  CONSTRAINT fk_DM_SUCURSAL_DM_UBIGEO1
    FOREIGN KEY (CODUBI)
    REFERENCES DM_UBIGEO (CODUBI)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE  DM_SEGMENTO (
  CODSEG VARCHAR(2) NOT NULL,
  DESSEG VARCHAR(50) NULL,
  PRIMARY KEY (CODSEG));


CREATE TABLE DM_CLIENTE (
  'CODCLI' INT NOT NULL,
  'TIPDOC' VARCHAR(1) NOT NULL,
  'NUMDOC' VARCHAR(20) NOT NULL,
  'NOMRAZSOC' VARCHAR(200) NOT NULL,
  'CODSEG' VARCHAR(2) NOT NULL,
  PRIMARY KEY ('CODCLI'),
  INDEX 'fk_DM_CLIENTE_DM_SEGMENTO1_idx' ('CODSEG' ASC),
  CONSTRAINT 'fk_DM_CLIENTE_DM_SEGMENTO1'
    FOREIGN KEY ('CODSEG')
    REFERENCES 'DM_SEGMENTO' ('CODSEG')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE  DM_USUARIO (
  CODUSU INT NOT NULL,
  APEPAT VARCHAR(100) NOT NULL,
  APEMAT VARCHAR(100) NOT NULL,
  NOMUSU VARCHAR(100) NOT NULL,
  PRIMARY KEY (CODUSU));


CREATE TABLE  DM_PERIODO (
  CODPER INT NOT NULL,
  ANIO INT NOT NULL,
  MES INT NOT NULL,
  DIA INT NOT NULL,
  NOMDIA VARCHAR(20) NOT NULL,
  TRIMESTRE VARCHAR(2) NOT NULL,
  NUMSEM INT NOT NULL,
  PRIMARY KEY (CODPER));

CREATE TABLE  FACT_VENTAS (
  CODPED VARCHAR(20)NOT NULL,
  CODPRO VARCHAR(6) NOT NULL,
  CODSUC VARCHAR(4) NOT NULL,
  CODCLI INT NOT NULL,
  CODPER INT NOT NULL,
  CODMES INT NOT NULL,
  CODCAJ INT NOT NULL,
  CANPRO INT NOT NULL,
  PREUNI DECIMAL NOT NULL,
  DSCPRO DECIMAL NOT NULL,
  TOTPRO DECIMAL NOT NULL,
  PRIMARY KEY (CODPED, CODPRO),
  INDEX fk_FACT_VENTAS_DM_PRODUCTO1_idx (CODPRO ASC) ,
  INDEX fk_FACT_VENTAS_DM_SUCURSAL1_idx (CODSUC ASC) ,
  INDEX fk_FACT_VENTAS_DM_CLIENTE1_idx (CODCLI ASC) ,
  INDEX fk_FACT_VENTAS_DM_PERIODO1_idx (CODPER ASC) ,
  INDEX fk_FACT_VENTAS_DM_USUARIO1_idx (CODMES ASC) ,
  INDEX fk_FACT_VENTAS_DM_USUARIO2_idx (CODCAJ ASC) ,
  CONSTRAINT fk_FACT_VENTAS_DM_PRODUCTO1
    FOREIGN KEY (CODPRO)
    REFERENCES DM_PRODUCTO (CODPRO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_FACT_VENTAS_DM_SUCURSAL1
    FOREIGN KEY (CODSUC)
    REFERENCES DM_SUCURSAL (CODSUC)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_FACT_VENTAS_DM_CLIENTE1
    FOREIGN KEY (CODCLI)
    REFERENCES DM_CLIENTE (CODCLI)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_FACT_VENTAS_DM_PERIODO1
    FOREIGN KEY (CODPER)
    REFERENCES DM_PERIODO (CODPER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_FACT_VENTAS_DM_USUARIO1
    FOREIGN KEY (CODMES)
    REFERENCES DM_USUARIO (CODUSU)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_FACT_VENTAS_DM_USUARIO2
    FOREIGN KEY (CODCAJ)
    REFERENCES DM_USUARIO (CODUSU)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


